export const blogData = [
  {
    id: 1,
    title: "Blog Example with MDX",
    slug: "blog-example-with-mdx-file",
    excerpt: "Blog Example with MDX That Comes with Templates",
    date: "2025-12-24",
    coverImage: "https://api.a0.dev/assets/image?text=Blog%20Example%20with%20MDX&aspect=1:1&seed=101",
  },
  {
    id: 2,
    title: "Bootstrap Template Guide",
    slug: "bootstrap-templates",
    excerpt: "Using Bootstrap Templates Downloaded from GrayGrids",
    date: "2025-12-24",
    coverImage: "https://api.a0.dev/assets/image?text=Bootstrap%20Template%20Guide&aspect=1:1&seed=102",
  },
  {
    id: 3,
    title: "Configuring Contact Form",
    slug: "contact-form",
    excerpt: "Configuring Contact Form That Comes with Templates",
    date: "2025-12-24",
    coverImage: "https://api.a0.dev/assets/image?text=Configuring%20Contact%20Form&aspect=1:1&seed=103",
  },
  {
    id: 4,
    title: "How to Customize Theme Colors in Bootstrap Templates",
    slug: "customize-theme-colors-bootstrap",
    excerpt: "A step-by-step guide to changing default theme colors in your Bootstrap templates.",
    date: "2025-12-20",
    coverImage: "https://api.a0.dev/assets/image?text=Customize%20Theme%20Colors%20Bootstrap&aspect=1:1&seed=104",
  },
  {
    id: 5,
    title: "Integrating FormBold with Your Contact Form",
    slug: "integrate-formbold-contact-form",
    excerpt: "Learn how to connect FormBold API to your contact forms for serverless submissions.",
    date: "2025-12-18",
    coverImage: "https://api.a0.dev/assets/image?text=Integrate%20FormBold%20Contact%20Form&aspect=1:1&seed=105",
  },
  {
    id: 6,
    title: "Best Plugins for Modern Web Templates",
    slug: "best-plugins-modern-web-templates",
    excerpt: "Our favorite JS and CSS plugins for adding interactivity to your web templates.",
    date: "2025-12-15",
    coverImage: "https://api.a0.dev/assets/image?text=Best%20Plugins%20Modern%20Web%20Templates&aspect=1:1&seed=106",
  },
  {
    id: 7,
    title: "Using Unsplash Images in Your Projects",
    slug: "using-unsplash-images-projects",
    excerpt: "How to find and use beautiful, free images from Unsplash in your web projects.",
    date: "2025-12-12",
    coverImage: "https://api.a0.dev/assets/image?text=Using%20Unsplash%20Images%20Projects&aspect=1:1&seed=107",
  },
  {
    id: 8,
    title: "Lineicons: The Icon Set for Modern UI",
    slug: "lineicons-modern-ui",
    excerpt: "Why Lineicons is our go-to icon set for modern web and SaaS UI design.",
    date: "2025-12-10",
    coverImage: "https://api.a0.dev/assets/image?text=Lineicons%20Modern%20UI&aspect=1:1&seed=108",
  },
  {
    id: 9,
    title: "Deploying Your Template to Production",
    slug: "deploying-template-production",
    excerpt: "A quick guide to uploading and launching your template on your own domain.",
    date: "2025-12-08",
    coverImage: "https://api.a0.dev/assets/image?text=Deploying%20Template%20Production&aspect=1:1&seed=109",
  },
];
